from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Campaign', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('company_name', models.CharField(max_length=255)),('brand_name', models.CharField(max_length=255)),('expected_doctors', models.PositiveIntegerField(default=0)),('contact_name', models.CharField(max_length=255)),('contact_phone', models.CharField(max_length=20)),('contact_email', models.EmailField(max_length=254)),('desktop_banner', models.FileField(blank=True, null=True, upload_to='banners/')),('mobile_banner', models.FileField(blank=True, null=True, upload_to='banners/')),('created_at', models.DateTimeField(auto_now_add=True)),('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'))]),
        migrations.CreateModel(name='CampaignSystem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('system', models.CharField(choices=[('red_flag', 'Red Flag Alerts'), ('patient', 'Patient Education'), ('inclinic', 'In-Clinic Education')], max_length=32)),('in_charge_name', models.CharField(blank=True, max_length=255)),('in_charge_designation', models.CharField(blank=True, max_length=255)),('items_per_clinic_per_year', models.PositiveIntegerField(default=0)),('start_date', models.DateField(blank=True, null=True)),('end_date', models.DateField(blank=True, null=True)),('contract_upload', models.FileField(blank=True, null=True, upload_to='contracts/')),('brand_logo', models.FileField(blank=True, null=True, upload_to='logos/')),('company_logo', models.FileField(blank=True, null=True, upload_to='logos/')),('printing_required', models.BooleanField(default=False)),('description', models.TextField(blank=True)),('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=16)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='education.campaign'))], options={'unique_together': {('campaign', 'system')}}),
        migrations.CreateModel(name='FieldRep', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('brand_rep_id', models.CharField(max_length=64)),('name', models.CharField(max_length=255)),('email', models.EmailField(max_length=254)),('phone', models.CharField(max_length=20)),('is_active', models.BooleanField(default=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reps', to='education.campaign'))], options={'unique_together': {('campaign', 'brand_rep_id')}}),
        migrations.CreateModel(name='RecruitmentLink', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.campaign'))]),
        migrations.CreateModel(name='Doctor', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=255)),('whatsapp_number', models.CharField(max_length=10)),('clinic_name', models.CharField(blank=True, max_length=255)),('created_at', models.DateTimeField(auto_now_add=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.campaign')),('field_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='education.fieldrep'))]),
        migrations.CreateModel(name='UserProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('role', models.CharField(choices=[('publisher', 'Publisher'), ('brand_manager', 'Brand Manager')], max_length=32)),('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'))]),
        migrations.CreateModel(name='Collateral', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('cycle', models.CharField(default='default', max_length=64)),('classification', models.CharField(choices=[('doctor_long', 'Doctor Education Long'), ('doctor_short', 'Doctor Education Short'), ('patient_long', 'Patient Education Long'), ('patient_short', 'Patient Education Short')], max_length=64)),('content_title', models.CharField(max_length=255)),('content_id', models.CharField(blank=True, max_length=255)),('item_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('both', 'PDF + Video')], max_length=10)),('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),('vimeo_url', models.URLField(blank=True)),('banner_1', models.FileField(blank=True, null=True, upload_to='collateral_banners/')),('banner_2', models.FileField(blank=True, null=True, upload_to='collateral_banners/')),('doctor_name', models.CharField(blank=True, max_length=255)),('content_description', models.TextField(blank=True)),('webinar_link', models.URLField(blank=True)),('webinar_title', models.CharField(blank=True, max_length=255)),('webinar_description', models.TextField(blank=True)),('webinar_date', models.DateField(blank=True, null=True)),('whatsapp_template', models.TextField(default='Please review: $collateralLinks')),('is_active', models.BooleanField(default=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='education.campaign')),('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.campaignsystem'))]),
        migrations.CreateModel(name='ShareInstance', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('short_code', models.CharField(max_length=24, unique=True)),('created_at', models.DateTimeField(auto_now_add=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.campaign')),('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.collateral')),('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.doctor')),('field_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.fieldrep'))]),
        migrations.CreateModel(name='Event', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),('event_type', models.CharField(choices=[('share_initiated', 'Share Initiated'), ('link_clicked', 'Link Clicked'), ('landing_access', 'Landing Page Access'), ('video_progress', 'Video Progress'), ('pdf_last_page', 'PDF Last Page Viewed'), ('pdf_downloaded', 'PDF Downloaded')], max_length=32)),('video_percentage', models.PositiveIntegerField(blank=True, null=True)),('created_at', models.DateTimeField(auto_now_add=True)),('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.campaign')),('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.collateral')),('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.doctor')),('field_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.fieldrep')),('share_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.shareinstance'))]),
        migrations.CreateModel(name='ReportingEvent', fields=[('id', models.UUIDField(primary_key=True, serialize=False)),('event_type', models.CharField(max_length=32)),('campaign_id', models.UUIDField()),('collateral_id', models.BigIntegerField()),('field_rep_id', models.BigIntegerField()),('doctor_id', models.BigIntegerField()),('share_instance_id', models.BigIntegerField()),('video_percentage', models.PositiveIntegerField(blank=True, null=True)),('created_at', models.DateTimeField())]),
    ]
